# Generated by Django 3.0.5 on 2020-04-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordAssociationSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this set of word associations', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WordAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('known_word', models.CharField(help_text='A word in a language you know', max_length=255)),
                ('learning_word', models.CharField(help_text="The word in the language you're learning", max_length=255)),
                ('word_set', models.ManyToManyField(help_text='The set of words this word appears in', to='flashcards.WordAssociationSet')),
            ],
            options={
                'unique_together': {('known_word', 'learning_word')},
            },
        ),
    ]
